### ISSUE TITLE
Task Tracking

### ISSUE THREAD

**Issue by hcltech84** [hcltech84/tutorial-get-started-with-go#1]
- [x] Install Go: `brew install go`
- [x] Write Hello World
- [x] Run Go code: `go run .`
- [x] Find packages
- [x] Call functions from external modules
